const Countries = [
  {value: '', label: 'World News'},
  {value: 'au', label: 'Australia'},
  {value: 'bs', label: 'Bahamas'},
  {value: 'be', label: 'Belgium'},
  {value: 'br', label: 'Brazil'},
  {value: 'cn', label: 'China'},
  {value: 'fr', label: 'France'},
  {value: 'gr', label: 'Greece'},
  {value: 'in', label: 'India'},
  {value: 'il', label: 'Israel'},
  {value: 'it', label: 'Italy'},
  {value: 'jm', label: 'Jamaica'},
  {value: 'kp', label: 'Korea, North'},
  {value: 'kr', label: 'Korea, South'},
  {value: 'nl', label: 'Netherlands'},
  {value: 'no', label: 'Norway'},
  {value: 'pk', label: 'Pakistan'},
  {value: 'ph', label: 'Phillipines'},
  {value: 'ru', label: 'Russia'},
  {value: 'sa', label: 'Saudi Arabia'},
  {value: 'se', label: 'Sweden'},
  {value: 'ch', label: 'Switzerland'},
  {value: 'tr', label: 'Turkey'},
  {value: 'vn', label: 'Vietnam'},
  {value: 'gb', label: 'United Kingdom'},
  {value: 'us', label: 'United States'},

];

export default Countries;
